course/course/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from common import views
from notes import views as notes_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="common/home.html"), name="home"),
    path("register/", views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="common/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="common/logout.html"),
        name="logout",
    ),
    path("<int:id>/", views.redirect_id_view, name="redirect_view"),
    path("search/", notes_views.form_view, name="search_form"),
    path("notes/", include(("notes.urls", "notes"), namespace="notes")),
    path("todo/", include(("todo.urls", "todo"), namespace="todo")),
]

course/notes/urls.py
from django.urls import path
from notes import views
from notes.views import SearchResultsView, NoteCreateView, NoteUpdateView

urlpatterns = [
    path("", views.notes_main_view, name="notes_main"),
    path("new/", NoteCreateView.as_view(), name="notes_new"),
    path("sections/", views.section_overview, name="section_overview"),
    path("sections/<str:section_name>", views.section_details, name="section_details"),
    path("sections/<slug:unique_slug>/", views.section_view, name="section_view"),
    path("<int:id>/", views.section_id_view, name="section_id_view"),
    path("<int:pk>/update/", NoteUpdateView.as_view(), name="notes_update"),
    # path("<str:search_text>/", views.search_view, name="search_text"),
    path("<str:search_term>/", SearchResultsView.as_view(), name="search"),
]

course/todo/urls.py
from django.contrib import admin
from django.urls import path

from todo import views

urlpatterns = [
    path("", views.todo_overview, name="todo_overview"),
    path("<int:id>/", views.todo_view, name="todo_view"),
]

course/common/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

course/common/views.py
from django.shortcuts import render, redirect, reverse
from django.contrib import messages
from .forms import UserRegisterForm


def overview_view(request):
    return render(request, "home.html")


def redirect_id_view(request, id):
    return redirect(reverse("section_id_view", args=(id)))


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(
                request, f"Account created for {username}! You are now able to login."
            )
            return redirect("login")
    else:
        form = UserRegisterForm()
    return render(request, "common/register.html", {"form": form})

course/common/templates/common/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% block title %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>

<body>
    <nav>
        <ul>
            <li><a href="{% url 'home'%}">Home</a></li>
            <li><a href="{% url 'notes:notes_main' %}">My Course Notes</a></li>
            <li><a href="{% url 'todo:todo_overview' %}">My ToDo List</a></li>
            {% if user.is_authenticated %}
                <li><a href="{% url 'logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'login' %}">Login</a></li>
                <li><a href="{% url 'register' %}">Register</a></li>
            {% endif %}
        </ul>
    </nav>
    
    <div>
        <h1>{% block header %}{% endblock %}</h1>
        {% if messages %}
        {% for message in messages %}
        <div>
            {{ message }}
        </div>
        {%endfor%}
        {% endif %}
        {% block content %}{% endblock %}
    </div>
    
    <footer>
        <p>Copyright &copy; iwona.com</p>
    </footer>
</body>

</html>

course/common/templates/common/home.html
{% extends "common/base.html" %}

{% block content %}
<div>
    <h1>Welcome to my new website!</h1>
    <p>Feel free to browse through my notes or check my ToDo list using the menu on the top.</p>
</div>

{% endblock content %}

course/common/templates/common/login.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div>
    <form method="POST">
        {% csrf_token %}
        <fieldset>
            <legend>Log In</legend>
            {{ form|crispy }}
        </fieldset>
        <div>
            <button type="submit">Log in</button>
        </div>
    </form>
    <div>
        <small>Need an account? <a href="{% url 'register' %}">Sign up here</a>
        </small>
    </div>
</div>
{% endblock %}

course/common/templates/common/logout.html
{% extends "common/base.html" %}

{% block content %}
    <h2>You have been logged out!</h2>
    <div>
        <small>Already have an account? <a href="{% url 'login' %}">Log in again</a>
        </small>
    </div>

{% endblock %}

course/common/templates/common/register.html
{% extends "common/base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div>
    <form method="POST">
        {% csrf_token %}
        <fieldset>
            <legend>Register here</legend>
            {{ form|crispy }}
        </fieldset>
        <div>
            <button type="submit">Sign up</button>
        </div>
    </form>
    <div>
        <small>Already have an account? <a href="#">Sign in</a>
        </small>
    </div>
</div>
{% endblock %}