course/course/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from common import views
from notes import views as notes_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="common/home.html"), name="home"),
    path("register/", views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="common/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="common/logout.html"),
        name="logout",
    ),
    path("<int:id>/", views.redirect_id_view, name="redirect_view"),
    path("search/", notes_views.form_view, name="search_form"),
    path("notes/", include(("notes.urls", "notes"), namespace="notes")),
    path("todo/", include(("todo.urls", "todo"), namespace="todo")),
]

course/notes/urls.py
from django.urls import path
from notes import views
from notes.views import SearchResultsView, NoteCreateView, NoteUpdateView

urlpatterns = [
    path("", views.notes_main_view, name="notes_main"),
    path("new/", NoteCreateView.as_view(), name="notes_new"),
    path("sections/", views.section_overview, name="section_overview"),
    path("sections/<str:section_name>", views.section_details, name="section_details"),
    path("sections/<slug:unique_slug>/", views.section_view, name="section_view"),
    path("<int:id>/", views.section_id_view, name="section_id_view"),
    path("<int:pk>/update/", NoteUpdateView.as_view(), name="notes_update"),
    # path("<str:search_text>/", views.search_view, name="search_text"),
    path("<str:search_term>/", SearchResultsView.as_view(), name="search"),
]

course/todo/urls.py
from django.contrib import admin
from django.urls import path

from todo import views

urlpatterns = [
    path("", views.todo_overview, name="todo_overview"),
    path("<int:id>/", views.todo_view, name="todo_view"),
]

course/notes/models.py
from django.db import models
from django.urls import reverse

SECTION_CHOICES = (
    ("Web Frameworks", "Web Frameworks"),
    ("URL Mapping", "URL Mapping"),
    ("Setting up Django", "Setting up Django"),
)


class Section(models.Model):
    title = models.CharField(max_length=500, choices=SECTION_CHOICES)
    note = models.TextField()
    slug = models.SlugField(unique=True)

    def get_absolute_url(self):
        return reverse("notes:section_id_view", kwargs={"id": self.id})

course/notes/forms.py
from django import forms

SECTION_TITLES = (
    ("any", "--Any--"),
    ("Web Frameworks", "Web Frameworks"),
    ("URL Mapping", "URL Mapping"),
    ("Setting up Django", "Setting up Django"),
)


class SearchForm(forms.Form):
    term_of_search = forms.CharField()
    section = forms.ChoiceField(choices=SECTION_TITLES, required=False)

course/notes/views.py
from django.shortcuts import render, redirect
from django.views.generic import FormView, TemplateView, CreateView, UpdateView
from django.urls import reverse
from notes import models
from notes.models import Section
from notes.forms import SearchForm
import logging

logger = logging.getLogger("django")


def notes_main_view(request):
    logger.info("User has visited page./ Info log")
    logger.debug(request)
    logger.warning(request, "This is a worning log")
    return render(request, "notes/main_overview.html")


def section_overview(request):
    sections = models.Section.objects.all()

    return render(
        request,
        "notes/sections_overview.html",
        {"sections": sections},
    )


def section_details(request, section_name):
    notes = models.Section.objects.filter(title=section_name)
    return render(
        request,
        "notes/section_details.html",
        {"notes": notes, "section_name": section_name},
    )


def section_view(request, unique_slug):
    section = models.Section.objects.filter(slug=unique_slug).first()
    return render(request, "notes/section.html", {"section": section})


def section_id_view(request, id):
    section = models.Section.objects.filter(id=id).first()
    previous_section = models.Section.objects.filter(id=id - 1).first()
    next_section = models.Section.objects.filter(id=id + 1).first()
    return render(
        request,
        "notes/section.html",
        {
            "section": section,
            "next_section": next_section,
            "previous_section": previous_section,
        },
    )


# def search_view(request, search_text):
#     section = models.Section.objects.filter(note__icontains=search_text).first()
#     return render(
#         request, "notes/search.html", {"section": section, "term": search_text}
#     )


class SearchResultsView(TemplateView):

    template_name = "notes/search_term.html"

    def get_context_data(self, search_term):
        sections = models.Section.objects.all()

        return {"sections": sections, "search_term": search_term}


# class SearchView(FormView):
#     template_name = "notes/search_form.html"
#     form_class = SearchForm

#     def get_success_url(self):
#         term_of_search = self.kwargs["term_of_search"]
#         return reverse("notes:search", args=[term_of_search])

#     def get_context_data(self, *args, **kwargs):
#         return {"my_form": SearchForm()}


def form_view(request):
    success_message = ""
    if request.method == "POST":
        form = SearchForm(request.POST)
        is_valid = form.is_valid()
        if is_valid:
            searched_term = request.POST.get("term_of_search")
            section = request.POST.get("section")
            return redirect(reverse("notes:search", args=(searched_term,)))
        else:
            message = "Form needs fixes!"
    else:
        form = SearchForm()
    return render(
        request,
        "notes/search_form.html",
        {"success_message": success_message, "form": form},
    )


class NoteCreateView(CreateView):
    model = Section
    fields = ["title", "note", "slug"]

    # def form_valid(self, form):
    #     form.instance.author = self.request.user
    #     return super().form_valid(form)

    # def form_valid(self, form):
    #     form.slug = self.request.form.get("title")
    #     return super().form_valid(form)


class NoteUpdateView(UpdateView):
    model = Section
    fields = ["title", "note", "slug"]

course/notes/templates/notes/base.html
{% extends "common/base.html" %}

{% block header %}My Notes{% endblock %}

{% block content %}{% endblock content %}

course/notes/templates/notes/main_overview.html
{% extends "common/base.html" %}

{% block content %}
<h2>Welcome to my course notes!</h2>
<p>
    <a href="{% url 'notes:section_overview'%}">Check the list of sections</a>
</p>
<p>
    <a href="{% url 'notes:section_id_view' 21 %}">Read my first notes</a>
</p>
<p>
    <a href="{% url 'search_form' %}">Search notes</a>
</p>
<p>
    <a href="{% url 'notes:notes_new' %}">Add a new note</a>
</p>
{% endblock content %}

course/notes/templates/notes/overview.html
{% extends "notes/base.html" %}

{% block content %}

{% for section in sections %}

<p>
<a href="{% url 'notes:section_view' section.slug %}">{{ section.title }}</a>
</p>
{% endfor %}

{% endblock %}

course/notes/templates/notes/search.html
{% extends "notes/base.html" %}

{% block content %}

<p>Search term: {{ term }}</p>

{% if section %}
<p>{{section.note}}</p>
{% else %}
The section could not be found.
{% endif %}

{% endblock %}

course/notes/templates/notes/search_form.html
{% extends "notes/base.html" %}

{% block content %}

<form method="post">
    {% csrf_token %}
  <label for="term_of_search">Term of search:</label>
  {{ form.term_of_search }}
  <label for="section">Section</label>
  {{ form.section }}
  <button type="submit">Submit</button>
  {{message}}
  </form>

  {% endblock %}

course/notes/templates/notes/search_term.html
{% extends "notes/base.html" %}

{% block content %}

<h4>Notes matching {{ search_term }}</h4>
  <ul>
    {% for section in sections %}
      {% if search_term|lower in section.note|lower|safe %}
        <li>
          {{ section.note }}
          <div><em>Filed under section <a href="{% url 'notes:section_view' section.slug %}">{{ section.title }}</a> </em></div>
        </li>
        
      {% endif %}
    {% endfor %}
  </ul>

{% endblock %}

course/notes/templates/notes/section.html
{% extends "notes/base.html" %}

{% load sections}

{% block content %}

{% if section %}
<h2>My note number {{ section.id }}</h2>

<h4>Section: <a href= "{% url 'notes:notes_main' %}">{{ section.title }}</a></h4>

<p>{{ section.note|safe }}</p>

{% else %}
The section could not be found.
{% endif %}

<p><a href="{% url 'notes:notes_update' section.id %}">Update</a></p>

{% if previous_section %}
<a href="{% url 'notes:section_id_view' previous_section.id %}">Previous</a>

{% endif %}
{% if next_section %}
<a href="{% url 'notes:section_id_view' next_section.id %}">Next</a>
{% endif %}
{% endblock %}

course/notes/templates/notes/section_details.html
{% extends "notes/base.html" %}

{% block content %}

<h2>Notes about {{section_name }}</h2>

<ol>
{% for item in notes %}

    {% if item.title == section_name %}
        <li>{{item.note}}</li>
        {% else %}
        continue
</ol>
{%endif %}
{% endfor %}

{% endblock %}

course/notes/templates/notes/section_form.html
{% extends "notes/base.html" %}
{%block content %}
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create" />
</form>
{% endblock %}

course/notes/templates/notes/sections_overview.html
{% extends "notes/base.html" %}

{% block content %}
<h2>Browse my notes by section</h2>



<ol>
    <li><a href="/notes/sections/Web%20Frameworks">Web Frameworks</a></li>
    <li><a href="/notes/sections/Setting%20up%20Django">Setting up Django</a></li>
    <li><a href="/notes/sections/URL%20Mapping">URL Mapping</a>
</ol>

{% endblock %}