course/course/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from common import views
from notes import views as notes_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="common/home.html"), name="home"),
    path("register/", views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="common/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="common/logout.html"),
        name="logout",
    ),
    path("<int:id>/", views.redirect_id_view, name="redirect_view"),
    path("search/", notes_views.form_view, name="search_form"),
    path("notes/", include(("notes.urls", "notes"), namespace="notes")),
    path("todo/", include(("todo.urls", "todo"), namespace="todo")),
]

course/todo/urls.py
from django.contrib import admin
from django.urls import path

from todo import views

urlpatterns = [
    path("", views.todo_overview, name="todo_overview"),
    path("<int:id>/", views.todo_view, name="todo_view"),
]

course/todo/models.py
from django.db import models


class Todo(models.Model):
    content = models.TextField()

course/todo/forms.py
from django import forms


class ValidateForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput())

course/todo/views.py
from django.shortcuts import render
from todo.forms import ValidateForm


# Create your views here.
from django.shortcuts import render

from todo import models


def todo_view(request, id):
    todo = models.Todo.objects.filter(id=id).first()
    previous_todo = models.Todo.objects.filter(id=id - 1).first()
    next_todo = models.Todo.objects.filter(id=id + 1).first()
    return render(
        request,
        "todo/todo.html",
        {"todo": todo, "previous_todo": previous_todo, "next_todo": next_todo},
    )


def todo_overview(request):

    if request.method == "POST":
        form = ValidateForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]

            if username == "admin" and password == "password":
                todos = models.Todo.objects.all()
                return render(request, "todo/overview.html", {"todos": todos})
        else:
            message = "Form needs fixes!"
    else:
        form = ValidateForm()
    return render(request, "todo/validate_form.html", {"form": form})

course/todo/templates/todo/overview.html
{% extends "common/base.html" %}

{% block header %}See our Todos{% endblock %}

{% block content %}
{% for todo in todos %}
<p>
<a href="{% url 'todo:todo_view' todo.id %}">{{todo.id}}.{{ todo.content }}</a>
</p>
{% endfor %}
{% endblock %}

course/todo/templates/todo/todo.html
{% extends "common/base.html" %}


{% block header %}TODO {{todo.id}}{% endblock %}

{% block content %}
{% if todo %}
<p>{{todo.content}}</p>
{% else %}
The todo item could not be found.
{% endif %}
{% if previous_todo %}
<a href="{% url 'todo:todo_view' previous_todo.id %}">Previous</a>

{% endif %}
{% if next_todo %}
<a href="{% url 'todo:todo_view' next_todo.id %}">Next</a>
{% endif %}
{% endblock %}

course/todo/templates/todo/validate_form.html
{% extends "common/base.html" %}

{% block content %}

<form method="post">
    {% csrf_token %}
  <label for="username">User name:</label>
  {{ form.username }}
  <label for="password">Password</label>
  {{ form.password }}
  <button type="submit">Submit</button>
  {{message}}
  </form>

  {% endblock %}